import Nav from "./components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-cols-10 p-8 h-screen w-full  bg-primary text-white/[10]">
        <Nav />
        {children}
      </body>
    </html>
  );
}
